name: Autotests-Saucedemo-Selenium

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          check-latest: true
      
      - name: Install Chrome browser
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install ChromeDriver
        run: |
          CHROME_DRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
          unzip ~/chromedriver_linux64.zip -d ~/
          rm ~/chromedriver_linux64.zip
          sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install requirements.txt
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and generate Allure results
        run: python -m pytest --alluredir=alluredir tests/
        env:
          GITHUB_ACTIONS: 'true'

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline

      - name: Generate Allure HTML report
        run: |
          allure generate alluredir -o allure-report --clean

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
